[package]
name = "silius"
version = { workspace = true }
authors = { workspace = true }
edition = { workspace = true }
license = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
description = """
AA (ERC-4337) bundler - Silius
"""

[dependencies]
anyhow = { workspace = true }
clap = { version = "4", features = ["derive"] }
dirs = "4.0"
ethers = { workspace = true }
expanded-pathbuf = { workspace = true }
log = "0.4.19"
pin-utils = "0.1"
revm = "3.3.0"
silius-bundler = { path = "../../crates/bundler" }
silius-grpc = { path = "../../crates/grpc" }
silius-primitives = { path = "../../crates/primitives" }
silius-rpc = { path = "../../crates/rpc" }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
